samples:
  C1_21:  /n/scratch3/users/s/sz166/CC/analysis/bowtie2/C1_21/C1_21.dedup.bam.filt
  C1_22:  /n/scratch3/users/s/sz166/CC/analysis/bowtie2/C1_22/C1_22.dedup.bam.filt
  C1_23:  /n/scratch3/users/s/sz166/CC/analysis/bowtie2/C1_23/C1_23.dedup.bam.filt
  C1_24:  /n/scratch3/users/s/sz166/CC/analysis/bowtie2/C1_24/C1_24.dedup.bam.filt
  C1_25:  /n/scratch3/users/s/sz166/CC/analysis/bowtie2/C1_25/C1_25.dedup.bam.filt
  C1_26:  /n/scratch3/users/s/sz166/CC/analysis/bowtie2/C1_26/C1_26.dedup.bam.filt
